// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWlEy6CeccXPwcStcnuFOfe3U4QXzU5JY',
    appId: '1:393707247884:web:51cd8dc68c1490871e1129',
    messagingSenderId: '393707247884',
    projectId: 'orbitask-d1669',
    authDomain: 'orbitask-d1669.firebaseapp.com',
    storageBucket: 'orbitask-d1669.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkTcYPQjJS4HoTVSBUWj10l7PFO-BOsHs',
    appId: '1:393707247884:android:7e9b8bbe63c9d0731e1129',
    messagingSenderId: '393707247884',
    projectId: 'orbitask-d1669',
    storageBucket: 'orbitask-d1669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9etxc90pcAC9Kbpe8km_haf4Pc4HAbIs',
    appId: '1:393707247884:ios:143c63951ccb05d61e1129',
    messagingSenderId: '393707247884',
    projectId: 'orbitask-d1669',
    storageBucket: 'orbitask-d1669.firebasestorage.app',
    iosBundleId: 'com.example.orbitask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9etxc90pcAC9Kbpe8km_haf4Pc4HAbIs',
    appId: '1:393707247884:ios:143c63951ccb05d61e1129',
    messagingSenderId: '393707247884',
    projectId: 'orbitask-d1669',
    storageBucket: 'orbitask-d1669.firebasestorage.app',
    iosBundleId: 'com.example.orbitask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWlEy6CeccXPwcStcnuFOfe3U4QXzU5JY',
    appId: '1:393707247884:web:cdb5061be2c091b61e1129',
    messagingSenderId: '393707247884',
    projectId: 'orbitask-d1669',
    authDomain: 'orbitask-d1669.firebaseapp.com',
    storageBucket: 'orbitask-d1669.firebasestorage.app',
  );
}
